# Mock service for TON integration
# In production, this would use tonpy or similar sdk to send the transaction
import hashlib
from datetime import datetime
import json

def register_hash_on_ton(document_hash: str, wallet_to: str) -> dict:
    """
    Simulates sending a transaction on TON with the document_hash in the memo/payload.
    """

    print(f"Mock TON: Creating tx to {wallet_to} with Memo={document_hash}")

    # Simulate a tx hash generated by the blockchain
    tx_base = f"{document_hash}-{datetime.utcnow().timestamp()}"
    simulated_tx_hash = hashlib.sha256(tx_base.encode('utf-8')).hexdigest()[:48]

    return {
        "status": "success",
        "tx_hash": simulated_tx_hash,
        "memo_used": document_hash,
        "network": "ton-mainnet-mock"
    }

if __name__ == "__main__":
    # Test execution
    res = register_hash_on_ton("a1b2c3d4e5f6...", "EQD...mock_wallet_address")
    print(json.dumps(res, indent=2))
